name: motionedit
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.16=he870216_1
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.4.0
      - albucore==0.0.33
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.1.0
      - bitsandbytes==0.45.3
      - cachetools==6.2.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.3.2
      - deepspeed==0.15.4
      # - diffusers==0.36.0.dev0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fastapi==0.115.11
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-aiplatform==1.71.1
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.5.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.0
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==2.0.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - peft==0.17.1
      - pillow==10.4.0
      - platformdirs==4.4.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.3
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.39.0
      - setproctitle==1.3.7
      - shapely==2.1.2
      - simsimd==6.5.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.2
      - stringzilla==4.0.14
      - sympy==1.13.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.21.4
      - torch==2.6.0
      - torchao==0.14.1
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.55.4
      - triton==3.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.34.0
      - vertexai==1.71.1
      - wandb==0.18.7
      - xformers==0.0.29.post3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /root/miniconda3/envs/motionedit
